name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry (No Virtualenv)
        run: poetry config virtualenvs.create false

      - name: Install Dependencies (Including Dev)
        run: poetry install --with dev

      - name: Run Tox
        run: tox
